### ISSUE TITLE
Custom columns don't work

### ISSUE THREAD

**Issue by janbaykara** [Markenson/csv-metabase-driver#18]
Getting an assortment of errors for [this CSV](https://github.com/commonknowledge/datadump/blob/main/HoC-GE2019-results-by-constituency-csv.csv).

Config settings:

- Filename: https://raw.githubusercontent.com/commonknowledge/datadump/master/
- Separator: ,
- Charset: utf-8
- Advanced: `&quotechar="&customTableList=HoC-GE2019-results-by-constituency-csv`

> Syntax error: derived tables not supported

<img width="1222" alt="Screenshot 2021-02-19 at 11 36 48" src="https://user-images.githubusercontent.com/237556/108499888-e78f5500-72a6-11eb-96b5-4e629a0a5cf3.png">

> Syntax error: Encountered " "AS" "AS "" at line 2, column 898. Was expecting: ")" ... 

<img width="949" alt="Screenshot 2021-02-19 at 11 37 10" src="https://user-images.githubusercontent.com/237556/108499883-e3fbce00-72a6-11eb-89ae-992f3be780b8.png">

Am I right in thinking this functionality isn't supported by this plugin?

**Comment by Markenson** [comment]
Hi @janbaykara! Probabily not.

Could you send the error logs, please? (Troubleshoot menu on administrative panel)

**Comment by janbaykara** [comment]
Here's the most recent logging I'm getting from the troubleshoot menu:

```
[62b2e534-5a13-44a6-9f48-0ac727f9a01a] 2021-02-23T03:57:00+00:00 INFO metabase.task.sync-databases Starting sync task for Database 7.
[62b2e534-5a13-44a6-9f48-0ac727f9a01a] 2021-02-23T03:57:00+00:00 INFO metabase.sync.util STARTING: Sync metadata for csv Database 7 'Constituency Marginality 2019'
[62b2e534-5a13-44a6-9f48-0ac727f9a01a] 2021-02-23T03:57:00+00:00 INFO metabase.sync.util FINISHED: step 'sync-timezone' for csv Database 7 'Constituency Marginality 2019' (283.5 µs)
[62b2e534-5a13-44a6-9f48-0ac727f9a01a] 2021-02-23T03:57:00+00:00 INFO metabase.sync.util STARTING: step 'sync-tables' for csv Database 7 'Constituency Marginality 2019'
[62b2e534-5a13-44a6-9f48-0ac727f9a01a] 2021-02-23T03:57:00+00:00 INFO metabase.sync.util STARTING: step 'sync-timezone' for csv Database 7 'Constituency Marginality 2019'
[62b2e534-5a13-44a6-9f48-0ac727f9a01a] 2021-02-23T03:57:00+00:00 INFO metabase.sync.util FINISHED: step 'sync-tables' for csv Database 7 'Constituency Marginality 2019' (182.6 ms)
[62b2e534-5a13-44a6-9f48-0ac727f9a01a] 2021-02-23T03:57:00+00:00 INFO metabase.sync.util STARTING: step 'sync-fields' for csv Database 7 'Constituency Marginality 2019'
[62b2e534-5a13-44a6-9f48-0ac727f9a01a] 2021-02-23T03:57:00+00:00 INFO metabase.sync.util FINISHED: step 'sync-fields' for csv Database 7 'Constituency Marginality 2019' (76.7 ms)
[62b2e534-5a13-44a6-9f48-0ac727f9a01a] 2021-02-23T03:57:00+00:00 INFO metabase.sync.util STARTING: step 'sync-fks' for csv Database 7 'Constituency Marginality 2019'
[62b2e534-5a13-44a6-9f48-0ac727f9a01a] 2021-02-23T03:57:00+00:00 INFO metabase.sync.util FINISHED: step 'sync-fks' for csv Database 7 'Constituency Marginality 2019' (1.4 ms)
[62b2e534-5a13-44a6-9f48-0ac727f9a01a] 2021-02-23T03:57:00+00:00 INFO metabase.sync.util STARTING: step 'sync-metabase-metadata' for csv Database 7 'Constituency Marginality 2019'
[62b2e534-5a13-44a6-9f48-0ac727f9a01a] 2021-02-23T03:57:00+00:00 INFO metabase.sync.util FINISHED: step 'sync-metabase-metadata' for csv Database 7 'Constituency Marginality 2019' (8.8 ms)
[62b2e534-5a13-44a6-9f48-0ac727f9a01a] 2021-02-23T03:57:00+00:00 INFO metabase.sync.util FINISHED: Sync metadata for csv Database 7 'Constituency Marginality 2019' (279.1 ms)
[62b2e534-5a13-44a6-9f48-0ac727f9a01a] 2021-02-23T03:57:00+00:00 INFO metabase.sync.util STARTING: Analyze data for csv Database 7 'Constituency Marginality 2019'
[62b2e534-5a13-44a6-9f48-0ac727f9a01a] 2021-02-23T03:57:00+00:00 INFO metabase.sync.analyze fingerprint-fields Analyzed [************······································] 😒   25% Table 74 'PUBLIC.HoC-GE2019-results-by-constituency-csv'
[62b2e534-5a13-44a6-9f48-0ac727f9a01a] 2021-02-23T03:57:00+00:00 INFO metabase.sync.util STARTING: step 'fingerprint-fields' for csv Database 7 'Constituency Marginality 2019'
[62b2e534-5a13-44a6-9f48-0ac727f9a01a] 2021-02-23T03:57:00+00:00 ERROR metabase.sync.util Error fingerprinting Table 74 'PUBLIC.HoC-GE2019-results-by-constituency-csv'
java.sql.SQLException: Syntax error: Encountered " "AS" "AS "" at line 2, column 2421.
Was expecting:
    ")" ...
    
	at org.relique.jdbc.csv.CsvPreparedStatement.<init>(CsvPreparedStatement.java:58)
	at org.relique.jdbc.csv.CsvConnection.prepareStatement(CsvConnection.java:863)
	at com.mchange.v2.c3p0.impl.NewProxyConnection.prepareStatement(NewProxyConnection.java:267)
	at metabase.driver.sql_jdbc.execute$fn__77381.invokeStatic(execute.clj:236)
	at metabase.driver.sql_jdbc.execute$fn__77381.invoke(execute.clj:234)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at metabase.driver.sql_jdbc.execute$prepared_statement_STAR_.invokeStatic(execute.clj:254)
	at metabase.driver.sql_jdbc.execute$prepared_statement_STAR_.invoke(execute.clj:251)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:387)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:374)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:383)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:374)
	at metabase.driver.sql_jdbc$fn__78967.invokeStatic(sql_jdbc.clj:54)
	at metabase.driver.sql_jdbc$fn__78967.invoke(sql_jdbc.clj:52)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at metabase.query_processor.context$executef.invokeStatic(context.clj:59)
	at metabase.query_processor.context$executef.invoke(context.clj:48)
	at metabase.query_processor.context.default$default_runf.invokeStatic(default.clj:68)
	at metabase.query_processor.context.default$default_runf.invoke(default.clj:66)
	at metabase.query_processor.context$runf.invokeStatic(context.clj:45)
	at metabase.query_processor.context$runf.invoke(context.clj:39)
	at metabase.query_processor.reducible$pivot.invokeStatic(reducible.clj:34)
	at metabase.query_processor.reducible$pivot.invoke(reducible.clj:31)
	at metabase.query_processor.middleware.mbql_to_native$mbql__GT_native$fn__46313.invoke(mbql_to_native.clj:25)
	at metabase.query_processor.middleware.check_features$check_features$fn__45589.invoke(check_features.clj:41)
	at metabase.query_processor.middleware.limit$limit$fn__46299.invoke(limit.clj:37)
	at metabase.query_processor.middleware.cache$maybe_return_cached_results$fn__45240.invoke(cache.clj:211)
	at metabase.query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__46478.invoke(optimize_datetime_filters.clj:133)
	at metabase.query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__44386.invoke(auto_parse_filter_values.clj:43)
	at metabase.query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__40767.invoke(wrap_value_literals.clj:147)
	at metabase.query_processor.middleware.annotate$add_column_info$fn__40630.invoke(annotate.clj:582)
	at metabase.query_processor.middleware.permissions$check_query_permissions$fn__45464.invoke(permissions.clj:69)
	at metabase.query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__47001.invoke(pre_alias_aggregations.clj:40)
	at metabase.query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__45662.invoke(cumulative_aggregations.clj:60)
	at metabase.query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__47314.invoke(resolve_joined_fields.clj:94)
	at metabase.query_processor.middleware.resolve_joins$resolve_joins$fn__47619.invoke(resolve_joins.clj:178)
	at metabase.query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__43976.invoke(add_implicit_joins.clj:181)
	at metabase.query_processor.middleware.large_int_id$convert_id_to_string$fn__46274.invoke(large_int_id.clj:44)
	at metabase.query_processor.middleware.format_rows$format_rows$fn__46254.invoke(format_rows.clj:74)
	at metabase.query_processor.middleware.desugar$desugar$fn__45728.invoke(desugar.clj:21)
	at metabase.query_processor.middleware.binning$update_binning_strategy$fn__44746.invoke(binning.clj:228)
	at metabase.query_processor.middleware.resolve_fields$resolve_fields$fn__45264.invoke(resolve_fields.clj:24)
	at metabase.query_processor.middleware.add_dimension_projections$add_remapping$fn__43606.invoke(add_dimension_projections.clj:316)
	at metabase.query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__43837.invoke(add_implicit_clauses.clj:146)
	at metabase.query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__48049.invoke(upgrade_field_literals.clj:45)
	at metabase.query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__44133.invoke(add_source_metadata.clj:124)
	at metabase.query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__47198.invoke(reconcile_breakout_and_order_by_bucketing.clj:97)
	at metabase.query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__44333.invoke(auto_bucket_datetimes.clj:139)
	at metabase.query_processor.middleware.resolve_source_table$resolve_source_tables$fn__45311.invoke(resolve_source_table.clj:45)
	at metabase.query_processor.middleware.parameters$substitute_parameters$fn__46983.invoke(parameters.clj:111)
	at metabase.query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__45363.invoke(resolve_referenced.clj:79)
	at metabase.query_processor.middleware.expand_macros$expand_macros$fn__45984.invoke(expand_macros.clj:155)
	at metabase.query_processor.middleware.add_timezone_info$add_timezone_info$fn__44142.invoke(add_timezone_info.clj:15)
	at metabase.query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__47985.invoke(splice_params_in_response.clj:32)
	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__47209$fn__47213.invoke(resolve_database_and_driver.clj:31)
	at metabase.driver$do_with_driver.invokeStatic(driver.clj:60)
	at metabase.driver$do_with_driver.invoke(driver.clj:56)
	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__47209.invoke(resolve_database_and_driver.clj:25)
	at metabase.query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46202.invoke(fetch_source_query.clj:264)
	at metabase.query_processor.middleware.store$initialize_store$fn__47994$fn__47995.invoke(store.clj:11)
	at metabase.query_processor.store$do_with_store.invokeStatic(store.clj:42)
	at metabase.query_processor.store$do_with_store.invoke(store.clj:38)
	at metabase.query_processor.middleware.store$initialize_store$fn__47994.invoke(store.clj:10)
	at metabase.query_processor.middleware.validate$validate_query$fn__48056.invoke(validate.clj:10)
	at metabase.query_processor.middleware.normalize_query$normalize$fn__46326.invoke(normalize_query.clj:22)
	at metabase.query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__43994.invoke(add_rows_truncated.clj:35)
	at metabase.query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__47970.invoke(results_metadata.clj:143)
	at metabase.query_processor.reducible$async_qp$qp_STAR___37408$thunk__37409.invoke(reducible.clj:103)
	at metabase.query_processor.reducible$async_qp$qp_STAR___37408.invoke(reducible.clj:109)
	at metabase.query_processor.reducible$sync_qp$qp_STAR___37417$fn__37420.invoke(reducible.clj:135)
	at metabase.query_processor.reducible$sync_qp$qp_STAR___37417.invoke(reducible.clj:134)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at metabase.query_processor$process_query.invokeStatic(query_processor.clj:146)
	at metabase.query_processor$process_query.doInvoke(query_processor.clj:140)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at clojure.lang.Var.invoke(Var.java:388)
	at metabase.db.metadata_queries$fn__59156$table_rows_sample__59165$fn__59168.invoke(metadata_queries.clj:144)
	at metabase.db.metadata_queries$fn__59156$table_rows_sample__59165.invoke(metadata_queries.clj:131)
	at metabase.sync.analyze.fingerprint$fn__59221$fingerprint_table_BANG___59226$fn__59227.invoke(fingerprint.clj:66)
	at metabase.sync.analyze.fingerprint$fn__59221$fingerprint_table_BANG___59226.invoke(fingerprint.clj:46)
	at metabase.sync.analyze.fingerprint$fn__59397$fingerprint_fields_BANG___59402$fn__59403$fn__59404.invoke(fingerprint.clj:180)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:146)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:139)
	at metabase.sync.analyze.fingerprint$fn__59397$fingerprint_fields_BANG___59402$fn__59403.invoke(fingerprint.clj:178)
	at metabase.sync.analyze.fingerprint$fn__59397$fingerprint_fields_BANG___59402.invoke(fingerprint.clj:174)
	at metabase.sync.analyze.fingerprint$fn__59432$fingerprint_fields_for_db_BANG__STAR___59441$fn__59444$fn__59445$fn__59446.invoke(fingerprint.clj:204)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$reduce.invoke(core.clj:6810)
	at metabase.sync.analyze.fingerprint$fn__59432$fingerprint_fields_for_db_BANG__STAR___59441$fn__59444$fn__59445.invoke(fingerprint.clj:200)
	at metabase.query_processor.store$do_with_store.invokeStatic(store.clj:44)
	at metabase.query_processor.store$do_with_store.invoke(store.clj:38)
	at metabase.sync.analyze.fingerprint$fn__59432$fingerprint_fields_for_db_BANG__STAR___59441$fn__59444.invoke(fingerprint.clj:197)
	at metabase.sync.analyze.fingerprint$fn__59432$fingerprint_fields_for_db_BANG__STAR___59441.invoke(fingerprint.clj:186)
	at metabase.sync.analyze.fingerprint$fn__59432$fingerprint_fields_for_db_BANG__STAR___59441$fn__59442.invoke(fingerprint.clj:191)
	at metabase.sync.analyze.fingerprint$fn__59432$fingerprint_fields_for_db_BANG__STAR___59441.invoke(fingerprint.clj:186)
	at metabase.sync.analyze.fingerprint$fn__59474$fingerprint_fields_for_db_BANG___59479$fn__59480.invoke(fingerprint.clj:218)
	at metabase.sync.analyze.fingerprint$fn__59474$fingerprint_fields_for_db_BANG___59479.invoke(fingerprint.clj:212)
	at metabase.sync.analyze$make_analyze_steps$fn__59631.invoke(analyze.clj:104)
	at metabase.sync.util$fn__39372$run_step_with_metadata__39377$fn__39381$fn__39383.invoke(util.clj:342)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:99)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:93)
	at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:116)
	at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:113)
	at metabase.sync.util$fn__39372$run_step_with_metadata__39377$fn__39381.invoke(util.clj:339)
	at metabase.sync.util$fn__39372$run_step_with_metadata__39377.invoke(util.clj:334)
	at metabase.sync.util$fn__39564$run_sync_operation__39569$fn__39570$fn__39571.invoke(util.clj:427)
	at clojure.core$mapv$fn__8445.invoke(core.clj:6912)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$mapv.invokeStatic(core.clj:6903)
	at clojure.core$mapv.invoke(core.clj:6903)
	at metabase.sync.util$fn__39564$run_sync_operation__39569$fn__39570.invoke(util.clj:427)
	at metabase.sync.util$fn__39564$run_sync_operation__39569.invoke(util.clj:421)
	at metabase.sync.analyze$fn__59643$analyze_db_BANG___59648$fn__59649$fn__59650.invoke(analyze.clj:121)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:146)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:139)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:142)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:139)
	at clojure.core$partial$fn__5839.invoke(core.clj:2623)
	at metabase.driver$fn__29100.invokeStatic(driver.clj:527)
	at metabase.driver$fn__29100.invoke(driver.clj:527)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__39284.invoke(util.clj:135)
	at metabase.sync.util$with_db_logging_disabled$fn__39281.invoke(util.clj:126)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:99)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:93)
	at metabase.sync.util$with_start_and_finish_logging$fn__39270.invoke(util.clj:111)
	at metabase.sync.util$with_sync_events$fn__39265.invoke(util.clj:85)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__39256.invoke(util.clj:64)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:161)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:158)
	at metabase.sync.analyze$fn__59643$analyze_db_BANG___59648$fn__59649.invoke(analyze.clj:118)
	at metabase.sync.analyze$fn__59643$analyze_db_BANG___59648.invoke(analyze.clj:113)
	at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invokeStatic(sync_databases.clj:70)
	at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invoke(sync_databases.clj:58)
	at metabase.task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
[62b2e534-5a13-44a6-9f48-0ac727f9a01a] 2021-02-23T03:57:00+00:00 INFO metabase.sync.util FINISHED: step 'fingerprint-fields' for csv Database 7 'Constituency Marginality 2019' (51.8 ms)
[62b2e534-5a13-44a6-9f48-0ac727f9a01a] 2021-02-23T03:57:00+00:00 INFO metabase.sync.util STARTING: step 'classify-fields' for csv Database 7 'Constituency Marginality 2019'
[62b2e534-5a13-44a6-9f48-0ac727f9a01a] 2021-02-23T03:57:00+00:00 INFO metabase.sync.analyze classify-fields Analyzed [*************************·························] 😬   50% Table 74 'PUBLIC.HoC-GE2019-results-by-constituency-csv'
[62b2e534-5a13-44a6-9f48-0ac727f9a01a] 2021-02-23T03:57:00+00:00 INFO metabase.sync.util FINISHED: step 'classify-fields' for csv Database 7 'Constituency Marginality 2019' (1.4 ms)
[62b2e534-5a13-44a6-9f48-0ac727f9a01a] 2021-02-23T03:57:00+00:00 INFO metabase.sync.util STARTING: step 'classify-tables' for csv Database 7 'Constituency Marginality 2019'
[62b2e534-5a13-44a6-9f48-0ac727f9a01a] 2021-02-23T03:57:00+00:00 INFO metabase.sync.analyze classify-tables Analyzed [*************************************·············] 😋   75% Table 74 'PUBLIC.HoC-GE2019-results-by-constituency-csv'
[62b2e534-5a13-44a6-9f48-0ac727f9a01a] 2021-02-23T03:57:00+00:00 INFO metabase.sync.util FINISHED: step 'classify-tables' for csv Database 7 'Constituency Marginality 2019' (1.6 ms)
[62b2e534-5a13-44a6-9f48-0ac727f9a01a] 2021-02-23T03:57:00+00:00 INFO metabase.sync.util FINISHED: Analyze data for csv Database 7 'Constituency Marginality 2019' (62.7 ms)
```

**Comment by michaywood** [comment]
I'm noticing this same issue

**Comment by willywildan** [comment]
same issue with me
