### ISSUE TITLE
Can't add any CSV DB (via https or not) on latest metabase versions (v0.41.6)

### ISSUE THREAD

**Issue by LucasDetre** [Markenson/csv-metabase-driver#28]
Hi,

I encounter an error when I try adding a new DB via CSV with this message : 

`No method in multimethod 'connection-details->spec' for dispatch value: :csv`

I'm using Metabase v0.41.6 which was released way after your last release which leads me to believe that the problem I encounter is linked to compatibility with the latests metabase versions.

Do you, by any chance, plan to update your plugin in the near future ?

Here are the logs of the error for the record :

```
2022-06-01 17:05:56,171 ERROR driver.util :: Erreur de connexion à la base de données
java.lang.IllegalArgumentException: No method in multimethod 'connection-details->spec' for dispatch value: :csv
	at clojure.lang.MultiFn.getFn(MultiFn.java:156)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at metabase.driver.sql_jdbc.connection$details__GT_connection_spec_for_testing_connection.invokeStatic(connection.clj:240)
	at metabase.driver.sql_jdbc.connection$details__GT_connection_spec_for_testing_connection.invoke(connection.clj:235)
	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invokeStatic(connection.clj:253)
	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invoke(connection.clj:249)
	at metabase.driver.sql_jdbc$fn__85180.invokeStatic(sql_jdbc.clj:35)
	at metabase.driver.sql_jdbc$fn__85180.invoke(sql_jdbc.clj:33)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at metabase.driver.util$can_connect_with_details_QMARK_$fn__24608.invoke(util.clj:43)
	at metabase.util$do_with_timeout$fn__6174.invoke(util.clj:353)
	at clojure.core$binding_conveyor_fn$fn__5772.invoke(core.clj:2034)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-06-01 17:05:56,174 ERROR api.database :: Ne peut pas se connecter à la base de données 
java.lang.Exception: No method in multimethod 'connection-details->spec' for dispatch value: :csv
	at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:48)
	at metabase.driver.util$can_connect_with_details_QMARK_.doInvoke(util.clj:31)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at metabase.api.database$test_database_connection.invokeStatic(database.clj:421)
	at metabase.api.database$test_database_connection.doInvoke(database.clj:411)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at metabase.api.database$fn__77164$test_connection_details__77169$fn__77170.invoke(database.clj:468)
	at metabase.api.database$fn__77164$test_connection_details__77169.invoke(database.clj:450)
	at metabase.api.database$fn__77196.invokeStatic(database.clj:488)
	at metabase.api.database$fn__77196.invoke(database.clj:474)
	at compojure.core$wrap_response$fn__32066.invoke(core.clj:160)
	at compojure.core$wrap_route_middleware$fn__32050.invoke(core.clj:132)
	at compojure.core$wrap_route_info$fn__32055.invoke(core.clj:139)
	at compojure.core$wrap_route_matches$fn__32059.invoke(core.clj:151)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078.invoke(core.clj:200)
	at metabase.server.middleware.auth$enforce_authentication$fn__70370.invoke(auth.clj:14)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078.invoke(core.clj:200)
	at compojure.core$make_context$handler__32106.invoke(core.clj:289)
	at compojure.core$make_context$fn__32110.invoke(core.clj:299)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$make_context$fn__32110.invoke(core.clj:300)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$make_context$fn__32110.invoke(core.clj:300)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$make_context$fn__32110.invoke(core.clj:300)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$make_context$fn__32110.invoke(core.clj:300)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$make_context$fn__32110.invoke(core.clj:300)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$make_context$fn__32110.invoke(core.clj:300)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at metabase.api.routes$fn__79847$fn__79850.invoke(routes.clj:56)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078.invoke(core.clj:200)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.server.routes$fn__79992$fn__79993.doInvoke(routes.clj:57)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078.invoke(core.clj:200)
	at compojure.core$make_context$handler__32106.invoke(core.clj:289)
	at compojure.core$make_context$fn__32110.invoke(core.clj:299)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32059.invoke(core.clj:153)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32059.invoke(core.clj:153)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32059.invoke(core.clj:153)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at metabase.server.routes$fn__79980$fn__79982.invoke(routes.clj:41)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078.invoke(core.clj:200)
	at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__77452.invoke(exceptions.clj:98)
	at metabase.server.middleware.exceptions$catch_api_exceptions$fn__77449.invoke(exceptions.clj:86)
	at metabase.server.middleware.log$log_api_call$fn__80447$fn__80448$fn__80449.invoke(log.clj:209)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invokeStatic(diagnostic.clj:15)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invoke(diagnostic.clj:9)
	at metabase.server.middleware.log$log_api_call$fn__80447$fn__80448.invoke(log.clj:201)
	at toucan.db$_do_with_call_counting.invokeStatic(db.clj:216)
	at toucan.db$_do_with_call_counting.invoke(db.clj:209)
	at metabase.server.middleware.log$log_api_call$fn__80447.invoke(log.clj:200)
	at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__83660.invoke(browser_cookie.clj:30)
	at metabase.server.middleware.security$add_security_headers$fn__59285.invoke(security.clj:147)
	at metabase.server.middleware.json$wrap_json_body$fn__82804.invoke(json.clj:62)
	at metabase.server.middleware.json$wrap_streamed_json_response$fn__82822.invoke(json.clj:98)
	at metabase.server.middleware.offset_paging$handle_paging$fn__59309.invoke(offset_paging.clj:42)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__83927.invoke(keyword_params.clj:55)
	at ring.middleware.params$wrap_params$fn__83943.invoke(params.clj:69)
	at metabase.server.middleware.misc$maybe_set_site_url$fn__34077.invoke(misc.clj:59)
	at metabase.server.middleware.session$bind_current_user$fn__44982$fn__44983.invoke(session.clj:257)
	at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:238)
	at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:230)
	at metabase.server.middleware.session$bind_current_user$fn__44982.invoke(session.clj:256)
	at metabase.server.middleware.session$wrap_current_user_info$fn__44969.invoke(session.clj:216)
	at metabase.server.middleware.session$wrap_session_id$fn__44955.invoke(session.clj:162)
	at metabase.server.middleware.auth$wrap_api_key$fn__70378.invoke(auth.clj:27)
	at ring.middleware.cookies$wrap_cookies$fn__83847.invoke(cookies.clj:216)
	at metabase.server.middleware.misc$add_content_type$fn__34060.invoke(misc.clj:27)
	at metabase.server.middleware.misc$disable_streaming_buffering$fn__34085.invoke(misc.clj:76)
	at ring.middleware.gzip$wrap_gzip$fn__83889.invoke(gzip.clj:86)
	at metabase.server.middleware.misc$bind_request$fn__34088.invoke(misc.clj:93)
	at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__83676.invoke(ssl.clj:48)
	at metabase.server$async_proxy_handler$fn__80220.invoke(server.clj:71)
	at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: No method in multimethod 'connection-details->spec' for dispatch value: :csv
	at clojure.lang.MultiFn.getFn(MultiFn.java:156)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at metabase.driver.sql_jdbc.connection$details__GT_connection_spec_for_testing_connection.invokeStatic(connection.clj:240)
	at metabase.driver.sql_jdbc.connection$details__GT_connection_spec_for_testing_connection.invoke(connection.clj:235)
	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invokeStatic(connection.clj:253)
	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invoke(connection.clj:249)
	at metabase.driver.sql_jdbc$fn__85180.invokeStatic(sql_jdbc.clj:35)
	at metabase.driver.sql_jdbc$fn__85180.invoke(sql_jdbc.clj:33)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at metabase.driver.util$can_connect_with_details_QMARK_$fn__24608.invoke(util.clj:43)
	at metabase.util$do_with_timeout$fn__6174.invoke(util.clj:353)
	at clojure.core$binding_conveyor_fn$fn__5772.invoke(core.clj:2034)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	... 1 more
```

Thank you for your time

**Comment by Markenson** [comment]
Hi @LucasDetre !

I'm going to check whats happening. Thank you for report this.

**Comment by Markenson** [comment]
I can't reproduce the error. I've recorded video below with latest version of metabase (0.43.4) today and it worked for me. Please try to reproduce the video steps and check if there are some difference between I did and what you doing.

Best Regards!

https://youtu.be/M4ccnTXiDtw

**Comment by jimenez-at-sagard** [comment]
Found same issue with v0.49.11
