### ISSUE TITLE
"Error: No method in multimethod 'connection-details->spec' for dispatch value: :csv"

### ISSUE THREAD

**Issue by ODonkiller** [Markenson/csv-metabase-driver#39]
Environment:

Metabase version: Metabase v0.50.14 (26d21b1)
CSV Driver version: Latest from the repository
Operating System: Running via Docker (Docker version 27.0.3, build 7d4bcd8)

![image](https://github.com/user-attachments/assets/abcdccf4-3c8a-45e8-8331-6f7222b0aba7)

java.lang.IllegalArgumentException: No method in multimethod 'connection-details->spec' for dispatch value: :csv
    at clojure.lang.MultiFn.getFn(MultiFn.java:156)
    at clojure.lang.MultiFn.invoke(MultiFn.java:233)
    at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection$fn__81404.invoke(connection.clj:313)
    at metabase.util.ssh$do_with_ssh_tunnel.invokeStatic(ssh.clj:165)
    at metabase.util.ssh$do_with_ssh_tunnel.invoke(ssh.clj:154)
    at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection.invokeStatic(connection.clj:312)
    at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection.invoke(connection.clj:308)
    at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invokeStatic(connection.clj:337)
    at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invoke(connection.clj:333)
    at metabase.driver.sql_jdbc$fn__109528.invokeStatic(sql_jdbc.clj:49)
    at metabase.driver.sql_jdbc$fn__109528.invoke(sql_jdbc.clj:47)
    at clojure.lang.MultiFn.invoke(MultiFn.java:234)
    at metabase.driver.util$can_connect_with_details_QMARK_$fn__56300.invoke(util.clj:149)
    at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: No method in multimethod 'connection-details->spec' for dispatch value: :csv
    at clojure.lang.MultiFn.getFn(MultiFn.java:156)
    at clojure.lang.MultiFn.invoke(MultiFn.java:233)
    at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection$fn__81404.invoke(connection.clj:313)
    ... 18 more

**Comment by met989** [comment]
I'm having the same problem with version v0.54.3
Operating System: Ubuntu 24.04.1
Java 21.0.6+7

**Comment by quantdynamixadmin** [comment]
+1 facing the same issue. Most probably this package is obsolete and needs upgrades to work.

**Comment by HonP** [comment]
The same problem here.
OpenJDK21U_21.0.7_6
Metabase - v0.55.2
